{{- range $localID, $vm := .Values.vms }}
{{- if eq $vm.location $.Values.location }}

{{- $effectiveID := include "sfs-iaas.spxEID" (dict "projectID" $.Values.projectID "localID" $localID) }}

{{- with $vm.volumes }}
{{- with .cloudInitNoCloud }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudinit-{{ $effectiveID }}
  labels:
    {{- include "sfs-iaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $effectiveID | quote }}
    superphenix.net/resourceLocalID: {{ $localID | quote }}
    superphenix.net/resourceName: {{ $vm.name | quote }}
stringData:
  userdata: |-
    {{- .userData | nindent 4 }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}