{{- range $localID, $key := .Values.ssh.publicKeys }}

{{- $keyID := include "sfs-iaas.spxEID" (dict "projectID" $.Values.projectID "localID" $localID) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $keyID | quote }}
  labels:
    {{- include "sfs-iaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $keyID | quote }}
    superphenix.net/resourceLocalID: {{ $localID | quote }}
    superphenix.net/resourceName: {{ $key.name | quote }}
stringData:
  spxSshKey: {{ .value | quote }}

{{- end }}