---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tuned.fullname" . }}-profiles
  labels:
    {{- include "tuned.labels" . | nindent 4 }}
data:
  {{- range $profile, $content := .Values.profiles }}
  {{ $profile }}: |
    {{- $content | nindent 4 }}
  {{- end }}
