apiVersion: v2
name: superphenix-system
description: A Helm chart for Superphenix cluster deployments
type: application
# This chart inherits the tag of the Git repository
version: 0.0.0
appVersion: "0.0.0"
