{{- range .Values.clusters }}
{{- if include "spx-ceph-conn.clusterEnabled" . }}
{{- $cluster := .name }}
{{- $csi := .csi | default dict }}
{{- range .blockPools }}
{{- range .storageClasses }}
{{- if and .encryption .encryption.enabled (eq (.encryption.kmsType | default "metadata") "metadata") }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- $scName := .fullName | default (printf "%s.%s" $cluster .name) }}
  name: {{ $scName }}-encryption
  namespace: {{ $csi.secretNamespace | default $cluster }}
stringData:
  encryptionPassphrase: {{ .encryption.passphrase | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
