apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.valuesConfigMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "superphenix-operator.labels" . | nindent 4 }}
data:
  argocd: |
    {{- toYaml .Values.config.argocd.values | nindent 4 }}
