{{- range .Values.clusters }}
{{- if and .rgwAdminOps (not .local) (include "spx-ceph-conn.clusterEnabled" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rgw-admin-ops-user
  namespace: {{ .name }}
type: kubernetes.io/rook
stringData:
  accessKey: {{ .rgwAdminOps.accessKey | quote }}
  secretKey: {{ .rgwAdminOps.secretKey | quote }}
{{- end }}
{{- end }}
