apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-test-secret
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  test-key: {{ .Values.testValue | default "hardcoded-test-value" | quote }}
