{{- range .Values.clusters }}
{{- if include "spx-ceph-conn.clusterEnabled" . }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    pod-security.kubernetes.io/enforce: privileged
{{- end }}
{{- end }}