apiVersion: operator.superphenix.net/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: superphenix-operator
    app.kubernetes.io/managed-by: kustomize
  name: cluster-sample
spec:
  deploymentMode: Hyperconverged
  region: us-east-1
  availabilityZone: us-east-1a
  networkConfiguration:
    mtu: 1500
    dns:
      - 8.8.8.8
      - 1.1.1.1
  systemConfiguration:
    timezone: UTC
    ntp:
      - pool.ntp.org
  connection:
    url: https://remote-cluster-api:6443
    secretRef:
      name: remote-cluster-creds
