---
apiVersion: v1
data:
  haproxy.cfg: |
    global
      maxconn 4000
      ssl-server-verify none
      hard-stop-after 1s
      log stderr format raw local0 debug

    defaults
      mode tcp
      timeout client 60m
      timeout server 60m
      timeout connect 5s
      # IPLB Client timeout 180s - Enable TCP_KEEPALIVE
      # To keep 6000sec of inactivity idle+cnt*intvl
      option srvtcpka
      srvtcpka-idle 150
      srvtcpka-cnt 23
      srvtcpka-intvl 150

    frontend healthz
      mode http
      bind "$HEALTHZ_BIND"
      monitor-uri /healthz

    frontend spf
      log global
      bind "$BIND":"$BIND_PORT"
      default_backend lb

    backend lb
      server lb "$ENDPOINT":"$PORT" ssl sni str("$ENDPOINT")
kind: ConfigMap
metadata:
  name: spx-apiproxy-conf
  namespace: kube-system

