{{- $controlPlane := $.Values.controlPlane -}}
{{- $apiServer := $controlPlane.network.apiServer -}}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: spx-apiserver-proxy
  name: spx-apiserver-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: spx-apiserver-proxy
  template:
    metadata:
      labels:
        k8s-app: spx-apiserver-proxy
    spec:
      initContainers:
      - name: init-api-proxy
        image: harbor.agc.dpk-agc-cl04.agoracalyce.net/docker-mirror/library/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', "ip link add api-proxy type dummy; ip addr add {{ $apiServer.address }}/32 dev api-proxy || :"]
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_ADMIN
      containers:
      - name: spx-apiserver-proxy
        env:
        - name: ENDPOINT
          value: {{ $controlPlane.fqdn }}
        - name: PORT
          value: "{{ $apiServer.proxyPort }}"
        - name: BIND
          value: {{ $apiServer.address }}
        - name: BIND_PORT
          value: "{{ $apiServer.port }}"
        - name: HEALTHZ_BIND
          value: 127.0.0.1:8134
        image: harbor.agc.dpk-agc-cl04.agoracalyce.net/docker-mirror/library/haproxy:alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: 8134
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        securityContext:
          capabilities:
            drop: 
            - ALL
        resources:
          requests:
            cpu: 2m
            memory: 10Mi
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: spx-apiproxy-vol
          readOnly: true
          subPath: haproxy.cfg
      hostNetwork: true
      priorityClassName: system-node-critical
      volumes:
      - configMap:
          items:
          - key: haproxy.cfg
            path: haproxy.cfg
          name: spx-apiproxy-conf
        name: spx-apiproxy-vol
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
