{{- range $name, $val := .Values.policies }}
{{- if eq $name "vm-credentials" }}

---
# ------------------------------------------------------------
# Check that all VirtualMachines' and VirtualMachineInstances'
# access credentials secret names are SPXIDs
# ------------------------------------------------------------
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: vap-{{ $name }}
  labels:
    {{- include "policies.labels" $ | nindent 4 }}
spec:
  variables:
    - name: spec
      expression: |
        object.kind == "VirtualMachine" ?
        object.spec.template.spec :
        object.spec
    - name: spxidRegex
      expression: r{{ include "policies.regex" "spxid" }}
  failurePolicy: Fail
  {{- include "policies.matchConditions" $val | nindent 2 }}
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    resourceRules:
      - apiGroups: ["kubevirt.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["virtualmachines", "virtualmachineinstances"]
        scope: '*'
  validations:
    # Check that accessCredentials secretName is an SPXID
    - expression: |
        !has(variables.spec.accessCredentials) ||
        variables.spec.accessCredentials.all(c,
          c.sshPublicKey.source.secret.secretName.matches(variables.spxidRegex)
        )
      messageExpression: |
        "##### " + object.kind +
        " has an incorrect credentials secretName regex (" +
        variables.spec.accessCredentials.filter(c,
          !c.sshPublicKey.source.secret.secretName.matches(variables.spxidRegex)
        ).map(entry, entry.sshPublicKey.source.secret.secretName)
        .join(", ") +
        "), must be an SPXID. #####"
      message: "##### Incorrect VM credentials secretName regex, must be an SPXID #####"

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: vap-{{ $name }}-binding
spec:
  policyName: vap-{{ $name }}
  validationActions: {{ $val.validationActions }}
  {{- include "policies.debug" $val | indent 2 }}
{{- end }}
{{- end }}