apiVersion: batch/v1
kind: CronJob
metadata:
  name: talos-backup
  namespace: talos-backup
spec:
  schedule: {{ .Values.cronjob.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: talos-backup
              image: {{ .Values.cronjob.image }}
              workingDir: /tmp
              imagePullPolicy: IfNotPresent
              command:
                - /talos-backup
              volumeMounts:
                - mountPath: /tmp
                  name: tmp
                - mountPath: /var/run/secrets/talos.dev
                  name: talos-secrets
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-secrets
                      key: accessKey
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-secrets
                      key: secretKey
                - name: AWS_REGION
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-secrets
                      key: region
                # CUSTOM_S3_ENDPOINT is optional; if omitted the service will fallback to default AWS endpoints.
                - name: CUSTOM_S3_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-secrets
                      key: endpointUrl
                - name: BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-secrets
                      key: bucket
                # CLUSTER_NAME is optional; if omitted it will fall back to the name of the default context.
                - name: CLUSTER_NAME
                  value: {{ .Values.cronjob.clusterName }}
                # S3_PREFIX is optional; if omitted it will fall back to the cluster name.
                - name: S3_PREFIX
                  value: "talos-backup"
                # AGE_X25519_PUBLIC_KEY supports multiple recipients as comma-separated keys
                - name: AGE_X25519_PUBLIC_KEY
                  value: {{ .Values.cronjob.agePubKey }}
                # ENABLE_COMPRESSION is optional; set this to true if you want to add compression to your etcd snapshot
                # If enabled, snapshot will be compressed with zstd algorithm
                - name: ENABLE_COMPRESSION
                  value: {{ .Values.cronjob.enableCompression | quote }}
          restartPolicy: OnFailure
          volumes:
            - emptyDir: {}
              name: tmp
            - name: talos-secrets
              secret:
                secretName: talos-backup-secrets

---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: talos-backup-secrets
  namespace: talos-backup
spec:
  roles:
    - os:etcd:backup

---
apiVersion: v1
kind: Secret
metadata:
  name: talos-backup-secrets
  namespace: talos-backup
  annotations:
    kubernetes.io/service-account.name: talos-backup-secrets
data:
  endpointUrl: {{ .Values.s3.endpointUrl }}
  bucket: {{ .Values.s3.bucket }}
  accessKey: {{ .Values.s3.accessKey }}
  secretKey: {{ .Values.s3.secretKey }}
  region: {{ .Values.s3.region }}