apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "superphenix-operator.fullname" . }}-manager-role
  labels:
    {{- include "superphenix-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - operator.superphenix.net
    resources:
      - clusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.superphenix.net
    resources:
      - clusters/finalizers
    verbs:
      - update
  - apiGroups:
      - operator.superphenix.net
    resources:
      - clusters/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "superphenix-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "superphenix-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "superphenix-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "superphenix-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
